---
- fail:
    msg: "Unsupported Java flavor ({{ eff_flavor }})!"
  when: eff_flavor not in flavor_support

- fail:
    msg: "The specified Java flavor ({{ eff_flavor }}) does not support the current Linux family ({{ ansible_os_family }})!"
  when: ansible_os_family | lower not in flavor_support[eff_flavor].families

- fail:
    msg: "The specified Java flavor ({{ eff_flavor }}) does not support the specified Java version ({{ eff_version }})!"
  when: eff_version | string not in flavor_support[eff_flavor].versions | string

- name: Check package manager architecture
  command:
    cmd: dpkg --print-architecture
  changed_when: false
  register: dpkg_arch
  when: ansible_os_family == 'Debian'
