---
# We could use Jinja to do it in one task, but this way at least I test both
# repo_file and repo_url.

- include_role:
    name: bviktor.thirdparty
  vars:
    name: "Amazon Corretto {{ eff_version }}"
    package: "java-{{ eff_version }}-amazon-corretto-jdk"
    gpg_url: 'https://apt.corretto.aws/corretto.key'
    repo_file: 'corretto'
    version: '' # need to 'unset' it, otherwise it collides with this role's version
  when: ansible_os_family == 'Debian'

- include_role:
    name: bviktor.thirdparty
  vars:
    name: "Amazon Corretto {{ eff_version }}"
    package: "java-{{ eff_version }}-amazon-corretto-devel"
    gpg_url: 'https://apt.corretto.aws/corretto.key'
    repo_url: 'https://yum.corretto.aws/corretto.repo'
    version: '' # need to 'unset' it, otherwise it collides with this role's version
  when: ansible_os_family == 'RedHat'
