---
# Debian:
# - openjdk-8-jre-headless
# - openjdk-11-jre-headless
# - openjdk-17-jre-headless
#
# EL:
# - java-1.8.0-openjdk-headless
# - java-11-openjdk-headless
# - java-17-openjdk-headless
#
# Facepalm...

- set_fact:
    eff_pkg_ver: "{% if ansible_os_family == 'RedHat' and eff_version | string == '8' %}1.8.0{% else %}{{ eff_version }}{% endif %}"

- name: "Install distro Java {{ eff_pkg_ver }}"
  apt:
    name: "openjdk-{{ eff_pkg_ver }}-jdk-headless"
    state: latest
    install_recommends: false
  when: ansible_os_family == 'Debian'

- name: "Install distro Java {{ eff_pkg_ver }}"
  dnf:
    name: "java-{{ eff_pkg_ver }}-openjdk-devel"
    state: latest
    install_weak_deps: false
  when: ansible_os_family == 'RedHat'

- set_fact:
    java:
      java_home: "/usr/lib/jvm/java-{{ eff_pkg_ver }}-openjdk{% if ansible_os_family == 'Debian' %}-{{ dpkg_arch.stdout_lines[0] }}{% endif %}"
