---
# Debian:
# - openjdk-8-jre-headless
# - openjdk-11-jre-headless
# - openjdk-17-jre-headless
#
# EL:
# - java-1.8.0-openjdk-headless
# - java-11-openjdk-headless
# - java-17-openjdk-headless
#
# Facepalm...

- set_fact:
    eff_pkg_ver: "{% if ansible_os_family == 'RedHat' and eff_version | string == '8' %}1.8.0{% else %}{{ eff_version }}{% endif %}"

- name: "Install distro Java {{ eff_pkg_ver }}"
  package:
    name: "{% if ansible_os_family == 'RedHat' %}java-{{ eff_pkg_ver }}-openjdk-headless{% else %}openjdk-{{ eff_pkg_ver }}-jre-headless{% endif %}"
    state: latest
