---
- include_role:
    name: bviktor.thirdparty
  vars:
    name: 'Microsoft Build of OpenJDK {{ eff_version }}'
    package: "msopenjdk-{{ eff_version }}"
    gpg_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    repo_file: 'microsoft-prod'
    version: '' # need to 'unset' it, otherwise it collides with this role's version

# TODO We'll almost certainly have to update this if MS becomes available on EL.
- set_fact:
    java:
      java_home: "/usr/lib/jvm/msopenjdk-{{ eff_version }}{% if ansible_os_family == 'Debian' %}-{{ dpkg_arch.stdout_lines[0] }}{% endif %}"
